Update Dockerfile

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -4,8 +4,9 @@ ARG UIDGID
 ARG USER
 
 # fail build if args are missing
-RUN if [ -z "$UIDGID" ]; then echo '\nERROR: UIDGID not set. Run \n\n \texport UIDGID=$(id -u):$(id -g) \n\n on host before building Dockerfile.\n'; exit 1; fi
 RUN if [ -z "$USER" ]; then echo '\nERROR: USER not set. Run \n\n \texport USER=$(whoami) \n\n on host before building Dockerfile.\n'; exit 1; fi
+RUN if [ -z "$UID" ]; then echo '\nERROR: UID not set. Run \n\n \texport UID=$(id -u) \n\n on host before building Dockerfile.\n'; exit 1; fi
+RUN if [ -z "$GID" ]; then echo '\nERROR: GID not set. Run \n\n \texport GID=$(id -g) \n\n on host before building Dockerfile.\n'; exit 1; fi
 
 # Prevent the interactive wizards from stopping the build
 ARG DEBIAN_FRONTEND=noninteractive
@@ -32,5 +33,13 @@ RUN cd /tmp/ws &&  \
     cargo build && \
     rm -rf /tmp/ws
 
-# chown working directory to user
-RUN mkdir -p /home/${USER}/ws && chown -R ${UIDGID} /home/${USER}
+# add the user so conan installs in the correct home directory, even though
+# when we log into the container parts of this will be mapped over
+RUN groupadd --gid ${GID} ${USER} \
+    && useradd --no-log-init --uid ${UID} --gid ${GID} -m ${USER} --groups sudo
+# grab the conanfile for installation
+WORKDIR /home/${USER}/ws
+# chown everything before we change users and run conan otherwise there
+# will be permission errors
+RUN chown -R ${UID}:${GID} /home/${USER}
+USER ${USER}
